#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8
grep -v -E "localhost|facebook.com" /etc/hosts > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
cat /tmp/hosts.tmp > /etc/hosts
rm -f /tmp/hosts.tmp
